# Generated by Django 5.2 on 2025-06-03 01:35

import NumerosPseudoaleatorios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistribucionBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BI', 'Binomial'), ('EXP', 'Exponencial')], max_length=3)),
                ('valores_x', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('valores_probabilidad', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('valores_acumulados', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('valores_x_simulados', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('valores_probabilidad_simulados', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('valores_acumulados_simulados', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('esperanza', models.FloatField()),
                ('varianza', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TesterBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CC', 'Chi-Cuadrado'), ('PK', 'Poker')], max_length=2)),
                ('significancia', models.FloatField(validators=[NumerosPseudoaleatorios.models.validar_significancia])),
                ('estadistico_prueba', models.FloatField()),
                ('valor_critico', models.FloatField()),
                ('aprobado', models.BooleanField()),
                ('frecuencias_observadas', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('frecuencias_esperadas', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('pvalor', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecuenciaBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CM', 'Congruencial Multiplicativo'), ('VN', 'Von Neumann')], max_length=2)),
                ('semilla', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(validators=[NumerosPseudoaleatorios.models.validar_cantidad])),
                ('cantidad_digitos', models.PositiveBigIntegerField(validators=[NumerosPseudoaleatorios.models.validar_cantidad_digitos])),
                ('numeros', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Binomial',
            fields=[
                ('distribucionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.distribucionbase')),
                ('p', models.FloatField(validators=[NumerosPseudoaleatorios.models.validar_probabilidad_exito])),
                ('n', models.PositiveIntegerField(validators=[NumerosPseudoaleatorios.models.validar_ensayos])),
            ],
            bases=('NumerosPseudoaleatorios.distribucionbase',),
        ),
        migrations.CreateModel(
            name='Exponencial',
            fields=[
                ('distribucionbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.distribucionbase')),
                ('tasa', models.FloatField(validators=[NumerosPseudoaleatorios.models.validar_tasa])),
            ],
            bases=('NumerosPseudoaleatorios.distribucionbase',),
        ),
        migrations.CreateModel(
            name='ChiCuadrado',
            fields=[
                ('testerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.testerbase')),
                ('cantidad_digitos', models.PositiveIntegerField(default=1, validators=[NumerosPseudoaleatorios.models.validar_cantidad_digitos])),
                ('intervalos', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_intervalos])),
            ],
            bases=('NumerosPseudoaleatorios.testerbase',),
        ),
        migrations.CreateModel(
            name='CongruencialMultiplicativo',
            fields=[
                ('secuenciabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.secuenciabase')),
                ('t', models.PositiveIntegerField()),
                ('p', models.PositiveIntegerField()),
                ('modulo', models.PositiveIntegerField()),
                ('multiplicador', models.BigIntegerField(editable=False)),
            ],
            bases=('NumerosPseudoaleatorios.secuenciabase',),
        ),
        migrations.CreateModel(
            name='VonNeumann',
            fields=[
                ('secuenciabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.secuenciabase')),
            ],
            bases=('NumerosPseudoaleatorios.secuenciabase',),
        ),
        migrations.AddField(
            model_name='testerbase',
            name='secuencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NumerosPseudoaleatorios.secuenciabase'),
        ),
        migrations.AddField(
            model_name='distribucionbase',
            name='secuencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NumerosPseudoaleatorios.secuenciabase'),
        ),
    ]
