# Generated by Django 5.1.7 on 2025-04-22 04:47

import NumerosPseudoaleatorios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecuenciaBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CM', 'Congruencial Multiplicativo'), ('VN', 'Von Neumann')], max_length=2)),
                ('semilla', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(validators=[NumerosPseudoaleatorios.models.validar_cantidad])),
                ('numeros', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CongruencialMultiplicativo',
            fields=[
                ('secuenciabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.secuenciabase')),
                ('t', models.PositiveIntegerField()),
                ('p', models.PositiveIntegerField()),
                ('modulo', models.PositiveIntegerField()),
                ('multiplicador', models.BigIntegerField(editable=False)),
            ],
            bases=('NumerosPseudoaleatorios.secuenciabase',),
        ),
        migrations.CreateModel(
            name='VonNeumann',
            fields=[
                ('secuenciabase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.secuenciabase')),
            ],
            bases=('NumerosPseudoaleatorios.secuenciabase',),
        ),
        migrations.CreateModel(
            name='TesterBase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CC', 'Chi-Cuadrado'), ('PK', 'Poker')], max_length=2)),
                ('significancia', models.FloatField(validators=[NumerosPseudoaleatorios.models.validar_significancia])),
                ('estadistico_prueba', models.FloatField()),
                ('valor_critico', models.FloatField()),
                ('aprobado', models.BooleanField()),
                ('frecuencias_observadas', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros])),
                ('pvalor', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('secuencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NumerosPseudoaleatorios.secuenciabase')),
            ],
        ),
    ]
