# Generated by Django 5.2 on 2025-06-06 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poker',
            fields=[
                ('testerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.testerbase')),
            ],
            bases=('NumerosPseudoaleatorios.testerbase',),
        ),
    ]
