# Generated by Django 5.2 on 2025-05-13 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionbase',
            name='secuencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NumerosPseudoaleatorios.secuenciabase'),
        ),
    ]
