# Generated by Django 5.2 on 2025-04-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secuenciabase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
