# Generated by Django 5.2 on 2025-06-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0002_poker'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testerbase',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='secuenciabase',
            old_name='cantidad',
            new_name='cantidad_inicial',
        ),
    ]
