# Generated by Django 5.2 on 2025-04-25 08:00

import NumerosPseudoaleatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0002_alter_secuenciabase_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testerbase',
            name='frecuencias_esperadas',
            field=models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros]),
        ),
    ]
