# Generated by Django 5.2 on 2025-05-13 20:02

import NumerosPseudoaleatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0002_distribucionbase_secuencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionbase',
            name='valores_acumulados_simulados',
            field=models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros]),
        ),
        migrations.AddField(
            model_name='distribucionbase',
            name='valores_x_simulados',
            field=models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros]),
        ),
    ]
