# Generated by Django 5.2 on 2025-04-25 10:37

import NumerosPseudoaleatorios.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0003_testerbase_frecuencias_esperadas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChiCuadrado',
            fields=[
                ('testerbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='NumerosPseudoaleatorios.testerbase')),
                ('cantidad_digitos', models.PositiveIntegerField(default=1, validators=[NumerosPseudoaleatorios.models.validar_cantidad_digitos])),
                ('intervalos', models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_intervalos])),
            ],
            bases=('NumerosPseudoaleatorios.testerbase',),
        ),
    ]
