# Generated by Django 5.2 on 2025-05-13 22:39

import NumerosPseudoaleatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0003_distribucionbase_valores_acumulados_simulados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionbase',
            name='valores_probabilidad_simulados',
            field=models.JSONField(default=list, validators=[NumerosPseudoaleatorios.models.validar_numeros]),
        ),
    ]
