# Generated by Django 5.2 on 2025-05-23 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0004_distribucionbase_valores_probabilidad_simulados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionbase',
            name='secuencia',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='NumerosPseudoaleatorios.secuenciabase'),
        ),
    ]
