# Generated by Django 5.2 on 2025-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0004_chicuadrado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testerbase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
