# Generated by Django 5.2 on 2025-05-29 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NumerosPseudoaleatorios', '0005_alter_distribucionbase_secuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribucionbase',
            name='secuencia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='NumerosPseudoaleatorios.secuenciabase'),
        ),
    ]
